version: '3.8'

services:

  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: naveen
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: demo-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres