spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/test?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=postgres
spring.datasource.password=naveen
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto = update

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

security.jwt.secret-key=ff93951f9c3a9a5b96baaf0183aee5d4dcd24440231ee353330bdcd78cbcd7cd
# 1h in millisecond
security.jwt.expiration-time=3600000

springdoc.api-docs.path=/api-docs

